language: cpp

os:
  - osx
  - linux

env:
- ENV=debug
- ENV=release

compiler: clang

addons:
  apt:
    packages:
    - libwxgtk3.0-dev
    - libwxgtk-webview3.0-dev

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then brew update       ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then brew install wxmac; fi
  - curl -L https://github.com/premake/premake-core/releases/download/v5.0.0-alpha10/premake-5.0.0-alpha10-macosx.tar.gz | tar xvz

script:
- ./premake5 gmake && make config=${ENV}_macos
