language: cpp

dist: trusty

sudo: required

services:
  - docker

os:
  - osx
  - linux

env:
- ENV=debug
- ENV=release
- ENV=test

compiler: clang

git:
  depth: 1

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make ENV=${ENV} PLATFORM=macos; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run -t -i -v `pwd`:/blitz3d-ng blitz3dng/blitz3d:latest make ENV=${ENV} PLATFORM=linux; fi

after_success:
  - if [[ "$ENV" == "test" ]]; then bash <(curl -s https://codecov.io/bash); fi
