language: cpp

dist: trusty

sudo: required

services:
  - docker

os:
  - osx
  - linux

env:
- ENV=debug
- ENV=release
- ENV=test

compiler: clang

git:
  depth: 1

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bundle install; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker-compose build; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make ENV=${ENV} PLATFORM=macos; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker-compose run env make ENV=${ENV} PLATFORM=linux; fi

after_success:
  - if [[ "$ENV" == "test" ]]; then bash <(curl -s https://codecov.io/bash); fi
