language: cpp

dist: trusty

sudo: required

services:
  - docker

os:
  - osx
  - linux

env:
- ENV=debug
- ENV=release
- ENV=test

compiler: clang

git:
  depth: 1

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bundle install; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -L https://github.com/premake/premake-core/releases/download/v5.0.0-alpha12/premake-5.0.0-alpha12-macosx.tar.gz | tar xvz; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker-compose build; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./bin/blitz3d config && ./premake5 gmake && make config=${ENV}_macos; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker-compose run -e "ENV=${ENV}" env; fi

after_success:
  - if [[ "$ENV" == "test" ]]; then bash <(curl -s https://codecov.io/bash); fi
