shallow_clone: true

os:
  - Visual Studio 2015

environment:
  matrix:
  - TOOLSET: vs2015

clone_script:
- cmd: >-
    git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%

install:
  - set PATH=C:\Ruby23-x64\bin;%PATH%
  - bundle install
  - ruby bin\blitz3d config
  - ps: Start-FileDownload 'https://github.com/premake/premake-core/releases/download/v5.0.0-alpha10/premake-5.0.0-alpha10-windows.zip' 'premake.zip'
  - 7z x premake.zip
  - premake5.exe %TOOLSET%

after_build:
  - cd %APPVEYOR_BUILD_FOLDER%\_release && 7z a bin\*.exe bin\*.dll cfg Games help Media mediaview samples tutorials userlibs Blitz3D.exe versions.txt

configuration:
  - debug
  - release

platform:
  - win32
  - win64

artifacts:
  - path: release.zip
    name: Full Release

  - path: _release\bin\runtime.*.dll
    name: Runtimes

  - path: _release\bin\blitzcc.exe
    name: Compiler

  - path: _release\bin\ide.exe
    name: IDE

build:
  parallel: true
  project: build/blitz3d.sln
