name: Default

modules:
  - blitz
  - runtime
  - hook
  - event
  - math
  - string
  - stream
  - sockets
  - system.windows
  - system.macos
  - filesystem.windows
  - timer.windows
  - bank
  - graphics.d3d7
  - input
  - input.directinput8
  - audio.fmod
  - blitz3d.d3d7
  - userlibs
  - runtime.windows
  - runtime.glfw3

premake5:
  - links:
    - stdutil

    - freeimage
    - jpeg
    - jxr
    - openexr
    - openjpeg
    - png
    - raw
    - tiff4
    - webp
    - zlib

  - filter: platforms:win32 or win64 or mingw32
  - links:
    - dinput8
    - fmodvc
    - dxguid
    - wsock32
    - winmm
    - dxguid
    - d3dxof
    - ddraw
    - dsound
    - kernel32
    - user32
    - gdi32
    - winspool
    - comdlg32
    - advapi32
    - shell32
    - ole32
    - oleaut32
    - uuid
    - odbc32
    - odbccp32

  - filter: platforms:win32 or win64
  - links: amstrmid

  - filter: platforms:mingw32
  - links: strmiids

  - filter: platforms:macos or linux
  - links: assimp
